//aqui van eventos DOM
const user = document.getElementById("user");
const search = document.getElementById("search");
const printMovie =  document.getElementById("printMovie");
let dataMovie = "";
const imgSugerencias= document.getElementById("sugerencias");
const home = document.getElementById("home");

// const printModal= document.getElementById("printModal");
home.addEventListener("click", () => {
    printMovie.innerHTML="";
    showGenre.innerHTML="";
});

search.addEventListener("click",()=>{
    const valueUser = user.value;
    console.log(valueUser);
    const url = `https://www.omdbapi.com/?apikey=60fc1083&s=${valueUser}`;
    fetch(url)
    .then(response => response.json())
    .then(data => {
        dataMovie = data.Search;
   // localStorage.setItem("data",JSON.stringify(dataMovie))
    forMovie (dataMovie);
   
    })
   
});
const forMovie = (dataMovie) =>{
    //dataMovie= JSON.parse(localStorage.getItem("data"));
    printMovie.innerHTML="";
    dataMovie.forEach(element => {
 let showMovie =
`<div class = "cardMovie">
<figure class ="imgMovie"><img class = "imagen"src = "${element.Poster}"></figure>
<div class ="infoMovie">
<h2>Title:${element.Title}</h2>
<p>Year: ${element.Year}</p>
<p>Type: ${element.Type}</p></div>
</div>`

  printMovie.insertAdjacentHTML("beforeend",showMovie)
    })
   }

function shiftLeft() {
    const boxes = document.querySelectorAll(".box");
    const tmpNode = boxes[0];
    boxes[0].className = "box move-out-from-left";

    setTimeout(function() {
        if (boxes.length > 5) {
            tmpNode.classList.add("box--hide");
            boxes[5].className = "box move-to-position5-from-left";
        }
        boxes[1].className = "box move-to-position1-from-left";
        boxes[2].className = "box move-to-position2-from-left";
        boxes[3].className = "box move-to-position3-from-left";
        boxes[4].className = "box move-to-position4-from-left";
        boxes[0].remove();

        document.querySelector(".cards__container").appendChild(tmpNode);

    }, 500);

}

function shiftRight() {
    const boxes = document.querySelectorAll(".box");
    boxes[4].className = "box move-out-from-right";
    setTimeout(function() {
        const noOfCards = boxes.length;
        if (noOfCards > 4) {
            boxes[4].className = "box box--hide";
        }

        const tmpNode = boxes[noOfCards - 1];
        tmpNode.classList.remove("box--hide");
        boxes[noOfCards - 1].remove();
        let parentObj = document.querySelector(".cards__container");
        parentObj.insertBefore(tmpNode, parentObj.firstChild);
        tmpNode.className = "box move-to-position1-from-right";
        boxes[0].className = "box move-to-position2-from-right";
        boxes[1].className = "box move-to-position3-from-right";
        boxes[2].className = "box move-to-position4-from-right";
        boxes[3].className = "box move-to-position5-from-right";
    }, 500);

}

arrayFiction = [
    {"Title":"Alien","Year":"1979","imdbID":"tt0078748","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Alien³","Year":"1992","imdbID":"tt0103644","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTNiYmQzNTctNzAyZC00ODY2LWE3ZjgtODU1NDA0NGI5ZDY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg"},{"Title":"Alien: Covenant","Year":"2017","imdbID":"tt2316204","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYzVkMjRhNzctOGQxMC00OGE2LWJhN2EtNmYyODRiMDNlM2ZmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg"},{"Title":"Alien: Resurrection","Year":"1997","imdbID":"tt0118583","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTdjYzU0MzAtZGMzOC00YTYwLWJhMTEtNDE4ODQwMDY2NWM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"AVP: Alien vs. Predator","Year":"2004","imdbID":"tt0370263","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTU4MjIwMTcyMl5BMl5BanBnXkFtZTYwMTYwNDA3._V1_SX300.jpg"},{"Title":"My Stepmother Is an Alien","Year":"1988","imdbID":"tt0095687","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzhiMjRlMDEtYzYwNi00MzY5LTlmZDgtOTM2ZDBjN2Y2N2FlXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg"},{"Title":"Alien Nation","Year":"1988","imdbID":"tt0094631","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjRlYjI2NWUtMmY5Mi00YTcyLTg5MzUtNTE2ZmRiMzNjYjA0XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg"},{"Title":"Alien Raiders","Year":"2008","imdbID":"tt0996979","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjRkMDY3NDAtYjQ3Zi00ZmJhLWJiOWEtNzc5NTllMjM3ZmY1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Alien Abduction","Year":"2014","imdbID":"tt2510434","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjMxMjUwMTU1Nl5BMl5BanBnXkFtZTgwOTI4NjMzMTE@._V1_SX300.jpg"},{"Title":"Alien Autopsy","Year":"2006","imdbID":"tt0466664","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTU0MDhkMmQtZGYzNS00MjFhLTk1NTAtN2ZkOGUxOTMxMWUxXkEyXkFqcGdeQXVyMjM4NjgwODc@._V1_SX300.jpg"},
    {"Title":"2001: A Space Odyssey","Year":"1968","imdbID":"tt0062622","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Office Space","Year":"1999","imdbID":"tt0151804","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_SX300.jpg"},{"Title":"Space Jam","Year":"1996","imdbID":"tt0117705","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDgyZTI2YmYtZmI4ZC00MzE0LWIxZWYtMWRlZWYxNjliNTJjXkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg"},{"Title":"Zathura: A Space Adventure","Year":"2005","imdbID":"tt0406375","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDc1NzM1OTgtOGYxMS00ZWE1LWEzZWMtNWEyOTI2NDJjOTU2XkEyXkFqcGdeQXVyNjQzNzA2NjM@._V1_SX300.jpg"},{"Title":"Space Cowboys","Year":"2000","imdbID":"tt0186566","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTk4NzAwOTkwMF5BMl5BanBnXkFtZTYwMDM3MTM3._V1_SX300.jpg"},{"Title":"Lost in Space","Year":"1998","imdbID":"tt0120738","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTkwNzEyNTgyN15BMl5BanBnXkFtZTcwODk4NTU0Mg@@._V1_SX300.jpg"},{"Title":"Lost in Space","Year":"2018–","imdbID":"tt5232792","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMjI3MjI5OTczNV5BMl5BanBnXkFtZTgwODA4MTc5NDM@._V1_SX300.jpg"},{"Title":"Star Trek: Deep Space Nine","Year":"1993–1999","imdbID":"tt0106145","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BODRkNGI5MWUtODU0MC00MzAyLWI3OTYtNTgwYTdkNTRmNjc2XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg"},{"Title":"The Space Between Us","Year":"2017","imdbID":"tt3922818","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjYzODU1OTkwN15BMl5BanBnXkFtZTgwMDA3MTMwMDI@._V1_SX300.jpg"},{"Title":"Plan 9 from Outer Space","Year":"1959","imdbID":"tt0052077","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzUzMzA0NDE3MF5BMl5BanBnXkFtZTgwMzg1Mjc1MDE@._V1_SX300.jpg"},
    {"Title":"Blade Runner","Year":"1982","imdbID":"tt0083658","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg"},{"Title":"Blade Runner 2049","Year":"2017","imdbID":"tt1856101","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg"},{"Title":"Blade","Year":"1998","imdbID":"tt0120611","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTQ4MzkzNjcxNV5BMl5BanBnXkFtZTcwNzk4NTU0Mg@@._V1_SX300.jpg"},{"Title":"Blade II","Year":"2002","imdbID":"tt0187738","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOWVjZTIzNDYtNTBlNC00NTJjLTkzOTEtOTE0MjlhYzI2YTcyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Blade: Trinity","Year":"2004","imdbID":"tt0359013","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjE0Nzg2MzI3MF5BMl5BanBnXkFtZTYwMjExODQ3._V1_SX300.jpg"},{"Title":"Sling Blade","Year":"1996","imdbID":"tt0117666","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNGY5NWIxMjAtODBjNC00MmZhLTk1ZTAtNGRhYThlOTNjMTQwXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg"},{"Title":"Dragon Blade","Year":"2015","imdbID":"tt3672840","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTk0MjgxOTQ5MF5BMl5BanBnXkFtZTgwODA3NTUwNjE@._V1_SX300.jpg"},{"Title":"Shinobi: Heart Under Blade","Year":"2005","imdbID":"tt0475723","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjAxMjE1NTEyMF5BMl5BanBnXkFtZTcwMDgxODkzMQ@@._V1_SX300.jpg"},{"Title":"Blade of the Immortal","Year":"2017","imdbID":"tt5084170","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYzIwYmJlMjktMzJiMy00YmQzLThmNWYtNWY3NGViZjc4MzYwXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SX300.jpg"},{"Title":"Blade Runner: Black Out 2022","Year":"2017","imdbID":"tt7428594","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZGNiNmNiMTctMDI4OS00OWYxLWE4ZWEtZjFkZjU4ZmY5YzEyXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_SX300.jpg"},
    {"Title":"The Matrix","Year":"1999","imdbID":"tt0133093","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg"},{"Title":"The Matrix Reloaded","Year":"2003","imdbID":"tt0234215","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg"},{"Title":"The Matrix Revolutions","Year":"2003","imdbID":"tt0242653","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzNlZTZjMDctZjYwNi00NzljLWIwN2QtZWZmYmJiYzQ0MTk2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"The Matrix Revisited","Year":"2001","imdbID":"tt0295432","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTIzMTA4NDI4NF5BMl5BanBnXkFtZTYwNjg5Nzg4._V1_SX300.jpg"},{"Title":"Enter the Matrix","Year":"2003","imdbID":"tt0277828","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4NTYwNjk0M15BMl5BanBnXkFtZTgwODk3MDMwMTE@._V1_SX300.jpg"},{"Title":"The Matrix: Path of Neo","Year":"2005","imdbID":"tt0451118","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BYWM2ZWU5MDUtYTU2ZS00ZDFmLWIyNGEtNWZkMjRmZjI2YzMzXkEyXkFqcGdeQXVyMTA1OTEwNjE@._V1_SX300.jpg"},{"Title":"Armitage III: Dual Matrix","Year":"2002","imdbID":"tt0303678","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTUwOTY3Mjg1MF5BMl5BanBnXkFtZTcwODI2MTAyMQ@@._V1_SX300.jpg"},{"Title":"CR: Enter the Matrix","Year":"2009","imdbID":"tt1675286","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMTExMzY3NTQ1NjleQTJeQWpwZ15BbWU3MDAyMjk2NzM@._V1_SX300.jpg"},{"Title":"Sex and the Matrix","Year":"2000","imdbID":"tt0274085","Type":"movie","Poster":"N/A"},{"Title":"Buhera mátrix","Year":"2007","imdbID":"tt0970173","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMGZiNzdmYWUtZTY0ZS00ZGU4LWE1NDgtNTNkZWM3MzQ0NDY4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjIzMDAwOTc@._V1_SX300.jpg"},
    {"Title":"Terminator 2: Judgment Day","Year":"1991","imdbID":"tt0103064","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg"},{"Title":"The Terminator","Year":"1984","imdbID":"tt0088247","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Terminator 3: Rise of the Machines","Year":"2003","imdbID":"tt0181852","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_SX300.jpg"},{"Title":"Terminator Salvation","Year":"2009","imdbID":"tt0438488","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODE1MTM1MzA2NF5BMl5BanBnXkFtZTcwODQ5MTA2Mg@@._V1_SX300.jpg"},{"Title":"Terminator Genisys","Year":"2015","imdbID":"tt1340138","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjM1NTc0NzE4OF5BMl5BanBnXkFtZTgwNDkyNjQ1NTE@._V1_SX300.jpg"},{"Title":"Terminator: The Sarah Connor Chronicles","Year":"2008–2009","imdbID":"tt0851851","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BZGE2ZDgyOWUtNzdiNS00OTI3LTkwZGQtMTMwNzM4YWUxNGNhXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_SX300.jpg"},{"Title":"Terminator 3: Rise of the Machines","Year":"2003","imdbID":"tt0364056","Type":"game","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5OTk4MTQwNV5BMl5BanBnXkFtZTgwMzkxNTEwMTE@._V1_SX300.jpg"},{"Title":"Terminator 2: Judgment Day","Year":"1991","imdbID":"tt0244839","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BN2FhOTQ2MmQtNTY0OC00NWYyLThjNjMtZmZiOTBmYTY4MmM2XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg"},{"Title":"Lady Terminator","Year":"1989","imdbID":"tt0095483","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYzgxMGFiMzQtZjNhNy00MzI4LTg1YzktZWJiNjRhZGRjZjJmXkEyXkFqcGdeQXVyNzMzMjU5NDY@._V1_SX300.jpg"},{"Title":"Ninja Terminator","Year":"1985","imdbID":"tt0199849","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMGZiNTczNWItOTdmYy00OTFjLWIwOWUtMmE3Y2QyNzBmZDJkXkEyXkFqcGdeQXVyNzg3NjQyOQ@@._V1_SX300.jpg"},
    {"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","imdbID":"tt0076759","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Star Wars: Episode V - The Empire Strikes Back","Year":"1980","imdbID":"tt0080684","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Star Wars: Episode VI - Return of the Jedi","Year":"1983","imdbID":"tt0086190","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Star Wars: Episode VII - The Force Awakens","Year":"2015","imdbID":"tt2488496","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_SX300.jpg"},{"Title":"Star Wars: Episode I - The Phantom Menace","Year":"1999","imdbID":"tt0120915","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTRhNjcwNWQtMGJmMi00NmQyLWE2YzItODVmMTdjNWI0ZDA2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Star Wars: Episode III - Revenge of the Sith","Year":"2005","imdbID":"tt0121766","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg"},{"Title":"Star Wars: Episode II - Attack of the Clones","Year":"2002","imdbID":"tt0121765","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDAzM2M0Y2UtZjRmZi00MzVlLTg4MjEtOTE3NzU5ZDVlMTU5XkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SX300.jpg"},{"Title":"Star Trek","Year":"2009","imdbID":"tt0796366","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"},{"Title":"Rogue One: A Star Wars Story","Year":"2016","imdbID":"tt3748528","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_SX300.jpg"},{"Title":"Star Wars: Episode VIII - The Last Jedi","Year":"2017","imdbID":"tt2527336","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjQ1MzcxNjg4N15BMl5BanBnXkFtZTgwNzgwMjY4MzI@._V1_SX300.jpg"},
    {"Title":"Avatar","Year":"2009","imdbID":"tt0499549","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg"},{"Title":"Avatar: The Last Airbender","Year":"2003–2008","imdbID":"tt0417299","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BNzZlZmQyYTgtOWNmMy00NTNhLTgyOTYtNjhiOTllOGU2MDg5XkEyXkFqcGdeQXVyMjYxMzY2NDk@._V1_SX300.jpg"},{"Title":"Avatar: The Last Airbender","Year":"2006","imdbID":"tt0959552","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BNjUwNzA5Nzc4N15BMl5BanBnXkFtZTgwNjM1ODY4MDE@._V1_SX300.jpg"},{"Title":"Avatar: The Game","Year":"2009","imdbID":"tt1517155","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYxODI2OTI4MF5BMl5BanBnXkFtZTcwNjI1NzMwMw@@._V1_SX300.jpg"},{"Title":"The King's Avatar","Year":"2017–","imdbID":"tt6859260","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BZjIyMjE5ZDYtMTQxNC00NTEzLTgwYzYtMmM0NDg3OWFlYWM5XkEyXkFqcGdeQXVyNjMxNzQ2NTQ@._V1_SX300.jpg"},{"Title":"Avatar: Creating the World of Pandora","Year":"2010","imdbID":"tt1599280","Type":"movie","Poster":"N/A"},{"Title":"Avatar: The Last Airbender - Into the Inferno","Year":"2008","imdbID":"tt1459460","Type":"game","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BOWFjYWUwZTMtNjM2Mi00YjU3LWI2NjQtZTNhOTRhM2Q3YmJkXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg"},{"Title":"The Guild: Do You Wanna Date My Avatar","Year":"2009","imdbID":"tt3051150","Type":"movie","Poster":"N/A"},{"Title":"Avatar: The Last Airbender - The Burning Earth","Year":"2007","imdbID":"tt1459461","Type":"game","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BM2M5N2FkY2EtMTJmMy00NjdmLWEwYmEtYjljOWI0MjQ1M2MyXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg"},{"Title":"Avatar","Year":"2005","imdbID":"tt0497595","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYmE4MmQwYTItMzUyZS00OGJmLWI3MWEtODg1Mzc1ZDI4YWQ4XkEyXkFqcGdeQXVyODI0NDU2Mw@@._V1_SX300.jpg"},
]

arrayAction = [
    {"Title":"Rambo","Year":"2008","imdbID":"tt0462499","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTI5Mjg1MzM4NF5BMl5BanBnXkFtZTcwNTAyNzUzMw@@._V1_SX300.jpg"},{"Title":"Rambo: First Blood Part II","Year":"1985","imdbID":"tt0089880","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZWFkY2I1ZDAtNmZhNS00NjVlLWJiMGQtMGQ1ZmM0ZDA5ODg5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Rambo III","Year":"1988","imdbID":"tt0095956","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTIwNWJhZDItZmNmOC00M2NkLWIwNDktMTYwZWFlZDVkMmVkL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Rambo","Year":"1986","imdbID":"tt0222619","Type":"series","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BOTVmMjU2ODItODk2NS00ZWJkLTgwOTEtZTMzZDNjNzhhZjkzXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg"},{"Title":"Rambo III","Year":"1989","imdbID":"tt0301766","Type":"game","Poster":"N/A"},{"Title":"Rambo: First Blood Part II","Year":"1986","imdbID":"tt0301768","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BNzRmM2EwYzAtZTMzNC00ZDg5LWE5YzktOWM5NTk4OGJhYWM4XkEyXkFqcGdeQXVyMjY3MjUzNDk@._V1_SX300.jpg"},{"Title":"Rambo","Year":"2012","imdbID":"tt3107798","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNDUwOGYwYWUtZjMzNi00MDIwLWE2NjgtYTdhODJmMTQwMGMyXkEyXkFqcGdeQXVyMzQzMDc2MDk@._V1_SX300.jpg"},{"Title":"Rambo","Year":"1987","imdbID":"tt0301765","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BYmMxZGVjYzYtNWY4ZC00ZjAwLWFjNWQtOWFjNGEzNDQ2ZDM3XkEyXkFqcGdeQXVyMTgwOTE5NDk@._V1_SX300.jpg"},{"Title":"Rambo: The Video Game","Year":"2014","imdbID":"tt4291054","Type":"game","Poster":"N/A"},{"Title":"Rambo","Year":"2003","imdbID":"tt0389308","Type":"movie","Poster":"N/A"},
    {"Title":"Kill Bill: Vol. 1","Year":"2003","imdbID":"tt0266697","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Kill Bill: Vol. 2","Year":"2004","imdbID":"tt0378194","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNmFiYmJmN2QtNWQwMi00MzliLThiOWMtZjQxNGRhZTQ1MjgyXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg"},{"Title":"To Kill a Mockingbird","Year":"1962","imdbID":"tt0056592","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNmVmYzcwNzMtMWM1NS00MWIyLThlMDEtYzUwZDgzODE1NmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Sin City: A Dame to Kill For","Year":"2014","imdbID":"tt0458481","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjA5ODYwNjgxMF5BMl5BanBnXkFtZTgwMTcwNzAyMjE@._V1_SX300.jpg"},{"Title":"A Time to Kill","Year":"1996","imdbID":"tt0117913","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOWExZTg4ZWYtOTQxMi00YWZkLTkxYzgtOTg1MTUxNzNiNDcxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Licence to Kill","Year":"1989","imdbID":"tt0097742","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODY3M2I0NGItYzJhNy00M2NiLThhMDgtNjZkNjA1NTQzMDM4XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg"},{"Title":"3 Days to Kill","Year":"2014","imdbID":"tt2172934","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzM0MjE0Nzg1N15BMl5BanBnXkFtZTgwODA4ODE4MDE@._V1_SX300.jpg"},{"Title":"Righteous Kill","Year":"2008","imdbID":"tt1034331","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYwMjg3MjY3OV5BMl5BanBnXkFtZTcwNTc4MDU3MQ@@._V1_SX300.jpg"},{"Title":"A View to a Kill","Year":"1985","imdbID":"tt0090264","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTZjNzJhOWYtMjZiNS00NmU2LTllYjAtOTAzMDk1NTI0ZTFkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg"},{"Title":"Generation Kill","Year":"2008","imdbID":"tt0995832","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTM2NjAxOTQzNl5BMl5BanBnXkFtZTcwMjk4NzU3MQ@@._V1_SX300.jpg"},
    {"Title":"Die Hard 2","Year":"1990","imdbID":"tt0099423","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzMzYzk3ZTEtZDg0My00MTY5LWE3ZmQtYzNhYjhjN2RhZGRjL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},
    {"Title":"Gladiator","Year":"2000","imdbID":"tt0172495","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg"},{"Title":"Gladiator","Year":"1992","imdbID":"tt0104346","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BM2U0NWE2ZDMtOGMzZS00MjRlLTgyNTItMTgwNTFjNjcyNDk2XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg"},{"Title":"The Gladiator","Year":"1986","imdbID":"tt0091121","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMzgwMDg5MV5BMl5BanBnXkFtZTcwMTcxNjcyMQ@@._V1_SX300.jpg"},{"Title":"Gladiator Cop","Year":"1995","imdbID":"tt0109905","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTcxNzg0NDc2NV5BMl5BanBnXkFtZTcwMDczODQyMQ@@._V1_SX300.jpg"},{"Title":"Gladiator Eroticvs: The Lesbian Warriors","Year":"2001","imdbID":"tt0256056","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTQwMDA5MDY1MV5BMl5BanBnXkFtZTcwMDI2NDIyMQ@@._V1_SX300.jpg"},{"Title":"Gladiator Days: Anatomy of a Prison Murder","Year":"2002","imdbID":"tt0359332","Type":"movie","Poster":"https://ia.media-imdb.com/images/M/MV5BMTIyNTM5NzU1Nl5BMl5BanBnXkFtZTcwNzQxNzYyMQ@@._V1_SX300.jpg"},{"Title":"Sheba and the Gladiator","Year":"1959","imdbID":"tt0051985","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjFmMjAwY2ItOGUyNS00Mzc5LWFhYmUtYmI2MWQzYjkxNTY0XkEyXkFqcGdeQXVyMDM0NzcxMQ@@._V1_SX300.jpg"},{"Title":"Strength and Honor: Creating the World of 'Gladiator'","Year":"2005","imdbID":"tt0456674","Type":"movie","Poster":"N/A"},{"Title":"See Ya Later Gladiator","Year":"1968","imdbID":"tt0063577","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZTA5Yzc4MjUtNmRkYy00NzYxLTg0ODItYTFmYmUxZWY4Yjc0XkEyXkFqcGdeQXVyNDE4OTY5NzI@._V1_SX300.jpg"},{"Title":"Gladiator of Rome","Year":"1962","imdbID":"tt0056026","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTk0MDAwNzcyM15BMl5BanBnXkFtZTcwMzA2MDc0NQ@@._V1_SX300.jpg"},
    {"Title":"Lethal Weapon","Year":"1987","imdbID":"tt0093409","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZTllNWNlZjctMWQwMS00ZDc3LTg5ZjMtNzhmNzhjMmVhYTFlXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg"},{"Title":"Lethal Weapon 2","Year":"1989","imdbID":"tt0097733","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTg0YmE1M2ItNGM2OC00MmZjLTgwMTMtZjlmOGE4N2EyNTVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Lethal Weapon 3","Year":"1992","imdbID":"tt0104714","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTFlNjI0NDQtMzlkNC00ZDU0LWE0ODktYmI2OTc2YjZlZmVlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Lethal Weapon 4","Year":"1998","imdbID":"tt0122151","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYmU2YTYwYmUtMTYzOC00YzJmLTk1NDktMzU4YzA3Njc1ZmY0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg"},{"Title":"Lethal Weapon","Year":"2016–","imdbID":"tt5164196","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMzMyNzM1MTczM15BMl5BanBnXkFtZTgwNDg4MzA0NjM@._V1_SX300.jpg"},{"Title":"Barely Lethal","Year":"2015","imdbID":"tt1731701","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjM4MzYyMjI1MV5BMl5BanBnXkFtZTgwMjE0Mzg2NTE@._V1_SX300.jpg"},{"Title":"Ghatak: Lethal","Year":"1996","imdbID":"tt0116407","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzJmZWFhZTgtM2I2Mi00YWE1LTgzODYtOTRlYWE3ODNmODgzXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg"},{"Title":"Lethal Vows","Year":"1999","imdbID":"tt0212304","Type":"movie","Poster":"https://ia.media-imdb.com/images/M/MV5BNjc2NTIzODI4MF5BMl5BanBnXkFtZTcwMjA1NzM4Nw@@._V1_SX300.jpg"},{"Title":"LD 50 Lethal Dose","Year":"2003","imdbID":"tt0337659","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTU1NTk4NzIxNF5BMl5BanBnXkFtZTcwMzU2OTcyMQ@@._V1_SX300.jpg"},{"Title":"Lethal Seduction","Year":"2015","imdbID":"tt4113114","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjI4MzA3NDA2N15BMl5BanBnXkFtZTgwODg1MTQzNzE@._V1_SX300.jpg"},
    {"Title":"Indiana Jones and the Last Crusade","Year":"1989","imdbID":"tt0097576","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg"},{"Title":"Indiana Jones and the Temple of Doom","Year":"1984","imdbID":"tt0087469","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMGI1NTk2ZWMtMmI0YS00Yzg0LTljMzgtZTg4YjkyY2E5Zjc0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Indiana Jones and the Kingdom of the Crystal Skull","Year":"2008","imdbID":"tt0367882","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTIxNDUxNzcyMl5BMl5BanBnXkFtZTcwNTgwOTI3MQ@@._V1_SX300.jpg"},{"Title":"The Young Indiana Jones Chronicles","Year":"1992–1993","imdbID":"tt0103586","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMzM0Nzk2MzkyOF5BMl5BanBnXkFtZTcwMDgxMjM4NA@@._V1_SX300.jpg"},{"Title":"Eerie, Indiana","Year":"1991–1992","imdbID":"tt0101088","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTUyNDQyMDQwM15BMl5BanBnXkFtZTcwMTIxMDcxMQ@@._V1_SX300.jpg"},{"Title":"Indiana Jones and the Fate of Atlantis","Year":"1992","imdbID":"tt0245165","Type":"game","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNDhmNTZjZDQtM2Y4OS00NWI3LWIzMGEtMTYxNGEzY2UwOWUzXkEyXkFqcGdeQXVyMzMxNDQ0NQ@@._V1_SX300.jpg"},{"Title":"Indiana Jones and the Temple of the Forbidden Eye Ride","Year":"1995","imdbID":"tt0764648","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzk5ZmEyMTgtYzQ0ZC00YTEwLWExOTUtMDZhZmY5NDQ0OGJlXkEyXkFqcGdeQXVyNzAyNzI4Njc@._V1_SX300.jpg"},{"Title":"The Adventures of Young Indiana Jones: Treasure of the Peacock's Eye","Year":"1995","imdbID":"tt0115031","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTg2MTc2NDAzOF5BMl5BanBnXkFtZTcwODExNDIyMQ@@._V1_SX300.jpg"},{"Title":"Lego Indiana Jones: The Original Adventures","Year":"2008","imdbID":"tt1149318","Type":"game","Poster":"N/A"},{"Title":"The Adventures of Young Indiana Jones: Attack of the Hawkmen","Year":"1995","imdbID":"tt0154004","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTcwMTU5NjExMV5BMl5BanBnXkFtZTYwNzU3MTA5._V1_SX300.jpg"},


]


arrayHorror = [
    {"Title":"Jaws","Year":"1975","imdbID":"tt0073195","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Jaws 2","Year":"1978","imdbID":"tt0077766","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BN2U1MWE1NTMtYjQ2ZC00MTFmLWFmYjItODMyNGYxOTAyZmEzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Jaws: The Revenge","Year":"1987","imdbID":"tt0093300","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNGI1MTAxMWItOTE0OC00ZDhkLWE3Y2EtNjFiZmQ4NjQ1NGNkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Jaws 3-D","Year":"1983","imdbID":"tt0085750","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BM2QwYjhiMzQtN2RiYS00MzgxLThmNzItMmJlNmMyMmQyYTA3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"The Making of 'Jaws'","Year":"1995","imdbID":"tt0251821","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjkxNTBmZDgtOGUwZS00N2IwLThiMTYtYzljYmU5NzE1MGQyXkEyXkFqcGdeQXVyNTUyNzA5ODE@._V1_SX300.jpg"},{"Title":"In the Jaws of Life","Year":"1984","imdbID":"tt0088312","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTIzNjU2ODUwOV5BMl5BanBnXkFtZTYwMzc2MDg4._V1_SX300.jpg"},{"Title":"Jaws of Satan","Year":"1981","imdbID":"tt0082580","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTUyOTY4Mzc0N15BMl5BanBnXkFtZTcwNTY2NjE2NA@@._V1_SX300.jpg"},{"Title":"Cruel Jaws","Year":"1995","imdbID":"tt0112747","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNDE2NTIzMjUtOTQ4ZC00ZWRlLTllZDAtNzZlNzRhNTRiNzA4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Mako: The Jaws of Death","Year":"1976","imdbID":"tt0074845","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODJiZmI1Y2ItMjBiNS00NGU0LTk2NmQtNGQ0YmVkYjNiNjlmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Jaws in Japan","Year":"2009","imdbID":"tt1786635","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxMzc3OTkyNV5BMl5BanBnXkFtZTcwMDA0NzMwNw@@._V1_SX300.jpg"},
    {"Title":"Scream","Year":"1996","imdbID":"tt0117571","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMjA2NjU5MTg5OF5BMl5BanBnXkFtZTgwOTkyMzQxMDE@._V1_SX300.jpg"},{"Title":"Scream 2","Year":"1997","imdbID":"tt0120082","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDNlM2E2OTUtZTRhZi00ZDU1LWIxODAtN2E5OGZiNmIwMDIwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Scream 4","Year":"2011","imdbID":"tt1262416","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTk5OTcxNTUyNF5BMl5BanBnXkFtZTcwMDczMzE0NA@@._V1_SX300.jpg"},{"Title":"Scream 3","Year":"2000","imdbID":"tt0134084","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDljNmI1YzctNjJlZC00NzZlLWFlZTgtMDE4MjJiMDk0ZGY4XkEyXkFqcGdeQXVyMjg3MDQ0Mjk@._V1_SX300.jpg"},{"Title":"Scream Queens","Year":"2015–2016","imdbID":"tt4145384","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTQ5MzU5NTE5NV5BMl5BanBnXkFtZTgwNjE0MzU3NTE@._V1_SX300.jpg"},{"Title":"Scream: The TV Series","Year":"2015–","imdbID":"tt3921180","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BNjVmY2M3ZTUtMDhkZC00ODk4LTkwMjktNDRjNGRjYTIxZGZiXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg"},{"Title":"Ice Cream, I Scream","Year":"2006","imdbID":"tt0816150","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BODRjMjdjZTAtYjgyMy00MWEzLTk5ZTQtNGQzM2I3MTgwN2FlXkEyXkFqcGdeQXVyMTg5MDIyNTk@._V1_SX300.jpg"},{"Title":"Scream of Fear","Year":"1961","imdbID":"tt0055505","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BM2M3MWZkN2MtYTFlYS00M2EzLWFmNzktNmMyMGNmMGQ1N2NmXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg"},{"Title":"Scream and Scream Again","Year":"1970","imdbID":"tt0064949","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTMyMzI1MjA3Ml5BMl5BanBnXkFtZTcwOTkyMTM4NA@@._V1_SX300.jpg"},{"Title":"Scream of the Banshee","Year":"2011","imdbID":"tt1548628","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTMwNTQ0MDQwMF5BMl5BanBnXkFtZTcwNjMzNjM1NA@@._V1_SX300.jpg"},
    {"Title":"Scouts Guide to the Zombie Apocalypse","Year":"2015","imdbID":"tt1727776","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTY4NjczNjE4OV5BMl5BanBnXkFtZTgwODk0MjQ5NjE@._V1_SX300.jpg"},{"Title":"Zombie","Year":"1979","imdbID":"tt0080057","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZTQzZTc3MjMtMGNiNy00ZTI1LWEwNjktYjVmODNmYjRiMGNiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTYxNjkxOQ@@._V1_SX300.jpg"},{"Title":"Zombie Strippers!","Year":"2008","imdbID":"tt0960890","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTI5MTM4NTA5MV5BMl5BanBnXkFtZTcwNzc0MTU2MQ@@._V1_SX300.jpg"},{"Title":"I Walked with a Zombie","Year":"1943","imdbID":"tt0036027","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZjQzMzliN2YtYTVhNC00Zjc4LThjMmYtMTE0ZGUzMWNmYzJlXkEyXkFqcGdeQXVyMTYxNjkxOQ@@._V1_SX300.jpg"},{"Title":"Scooby-Doo on Zombie Island","Year":"1998","imdbID":"tt0166792","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzA1ZmMyYjUtMjMzOS00NGRmLTkzMzQtZmVmN2ExMWI1NjJiXkEyXkFqcGdeQXVyNjg1MDQzMzc@._V1_SX300.jpg"},{"Title":"Zombie Nation","Year":"2004","imdbID":"tt0463392","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTczNjE5Njk5Ml5BMl5BanBnXkFtZTcwNDc3MDA0MQ@@._V1_SX300.jpg"},{"Title":"White Zombie","Year":"1932","imdbID":"tt0023694","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjEwODU3MDI1OF5BMl5BanBnXkFtZTgwODY4NzYwMjE@._V1._CR81.88333129882812,101.53334045410156,1038,1572.249984741211_SX89_AL_.jpg_V1_SX300.jpg"},{"Title":"Zombie Apocalypse","Year":"2011","imdbID":"tt1876547","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTM3MTEzNjgxM15BMl5BanBnXkFtZTcwMTQyNTA5Ng@@._V1_SX300.jpg"},{"Title":"Zombie Holocaust","Year":"1980","imdbID":"tt0079788","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYTc1YzgxNzktMWY4Mi00ZmUwLTkwODktMzAwZDUwMzA0YTRhXkEyXkFqcGdeQXVyMzMwMjI2NA@@._V1_SX300.jpg"},{"Title":"The Zombie Diaries","Year":"2006","imdbID":"tt0876294","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTc0NTk4NjMzOF5BMl5BanBnXkFtZTcwMzk2OTIwMg@@._V1_SX300.jpg"},
    {"Title":"Bram Stoker's Dracula","Year":"1992","imdbID":"tt0103874","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYyOTM5NzU3Nl5BMl5BanBnXkFtZTgwOTQxNjAxNzE@._V1_SX300.jpg"},{"Title":"Dracula Untold","Year":"2014","imdbID":"tt0829150","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTkzNzI1OTI4N15BMl5BanBnXkFtZTgwNTQ2NzEwMjE@._V1_SX300.jpg"},{"Title":"Dracula","Year":"1931","imdbID":"tt0021814","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZDY2ODZhZWQtNDk0ZS00OGE4LWE4NjAtZjE5MTJhMjExMTRjXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg"},{"Title":"Dracula: Dead and Loving It","Year":"1995","imdbID":"tt0112896","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZWQ0ZDFmYzMtZGMyMi00NmYxLWE0MGYtYzM2ZGNhMTE1NTczL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjM5ODMxODc@._V1_SX300.jpg"},{"Title":"Dracula 2000","Year":"2000","imdbID":"tt0219653","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYzUxYzFlZjYtYWNiOC00ZmY0LThjMjYtMDdlNmRhNmY5MDRjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Dracula","Year":"2013–2014","imdbID":"tt2296682","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMzEzZTIyYjAtODY0Zi00NjhlLWJkOTItMjE0YjBkZDczMTA3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg"},{"Title":"Horror of Dracula","Year":"1958","imdbID":"tt0051554","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOGI5YTA5OTMtNDc1Yy00YTc2LTg2MDUtNjdiYzBkZmZkMzVlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg"},{"Title":"Dracula","Year":"1979","imdbID":"tt0079073","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODcxNWU1MzktNzc4MC00YWI3LTllNzktNDY5YmJhMjNiN2YwXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg"},{"Title":"Dracula: Prince of Darkness","Year":"1966","imdbID":"tt0059127","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZDZiNWEzNTgtMDNkYS00YWY3LTg3ZmUtZDllMDFhZDUwYjIwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"The Batman vs. Dracula","Year":"2005","imdbID":"tt0472219","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTkyMTMwNjA3MV5BMl5BanBnXkFtZTcwNzE2NTI2OQ@@._V1_SX300.jpg"},
    {"Title":"Hellraiser","Year":"1987","imdbID":"tt0093177","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTkyNzc4NjkwNV5BMl5BanBnXkFtZTgwNzI2Mjc1MDE@._V1_SX300.jpg"},{"Title":"Hellbound: Hellraiser II","Year":"1988","imdbID":"tt0095294","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzIxZjA2MzAtZTU5MS00N2FjLWI2NDQtNGMwYzQxMGE1NDlmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser III: Hell on Earth","Year":"1992","imdbID":"tt0104409","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTRiMGFjMmMtYTUzOS00N2U4LWJjZDQtNjFjNjg4MTg4YTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Bloodline","Year":"1996","imdbID":"tt0116514","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzM1NjVhNGUtY2FhNy00MTQ4LTkyNDAtZWE2YWZhYWQ2YzdmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Inferno","Year":"2000","imdbID":"tt0229440","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZTJkYzI4ZGQtYTU3Yy00MWU1LWE3NjUtZjI5Zjc2ZGI0Mjc5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Hellseeker","Year":"2002","imdbID":"tt0274546","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDBlNGVkZDctNGIzYi00OGZjLTg3ZDktZTM4NmNkZDEzMjZlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Hellworld","Year":"2005","imdbID":"tt0354623","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZDM2OGViNjAtMmM5OS00YzJiLTgzODItNTZlYzcxNjAyZDUyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Deader","Year":"2005","imdbID":"tt0337636","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTIyYTAzZjEtOTEzYS00NTliLWE0MjYtM2FiZGYzYTQxMWM5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Revelations","Year":"2011","imdbID":"tt1716747","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZmQ2ZTY0MmYtNjM2Ny00MTIxLWIxNGUtMTlhYWQyYjBhY2IxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Hellraiser: Judgment","Year":"2018","imdbID":"tt5476182","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYzZmOTE0NTktZWQ2Zi00NDhhLTkwYmQtNWRmZGZhNjMxNDdmXkEyXkFqcGdeQXVyOTE2MTYxOQ@@._V1_SX300.jpg"},
    {"Title":"[Rec]","Year":"2007","imdbID":"tt1038988","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZTJmNTZlZWUtZTQ2Yi00YTFjLWFiNzctYzFlNmZmZGMzYTlmXkEyXkFqcGdeQXVyMjQ2MTk1OTE@._V1_SX300.jpg"},{"Title":"[Rec] 2","Year":"2009","imdbID":"tt1245112","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTI4MjQ1MDE1MV5BMl5BanBnXkFtZTcwNzIxMDk0Mw@@._V1_SX300.jpg"},{"Title":"[REC] 3: Genesis","Year":"2012","imdbID":"tt1649444","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNDM3OTUzMTA1OF5BMl5BanBnXkFtZTcwNTkwMTE3Nw@@._V1_SX300.jpg"},{"Title":"[REC] 4: Apocalypse","Year":"2014","imdbID":"tt1649443","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOTU3OTU2ODc5MF5BMl5BanBnXkFtZTgwNjY3MDY2MzE@._V1_SX300.jpg"},{"Title":"Rec","Year":"2006–","imdbID":"tt0807834","Type":"series","Poster":"https://ia.media-imdb.com/images/M/MV5BYWY2NDRiZDAtNGJmNy00ODUzLWFjNzItOTQzMTU1MjdkOTJkXkEyXkFqcGdeQXVyNTQzMjAxMzA@._V1_SX300.jpg"},{"Title":"[REC]³ Génesis: preparativos de una boda sangrienta","Year":"2012","imdbID":"tt2378603","Type":"movie","Poster":"N/A"},{"Title":"[Rec] 2: En un mundo de infectados","Year":"2010","imdbID":"tt1570501","Type":"movie","Poster":"N/A"},{"Title":"REC [Al-i-ssi]","Year":"2011","imdbID":"tt2179602","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjFjOTJmZjktMmMxOC00YmU2LTk5NTUtMTcxOWQ4OTI2MjdjXkEyXkFqcGdeQXVyNjUzMDYwNTc@._V1_SX300.jpg"},{"Title":"I rec u","Year":"2012","imdbID":"tt2773034","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZWY5YjU2OGItNTRhNC00NDk3LWI1MWEtZTdjOGExNjg2ZTAxXkEyXkFqcGdeQXVyMzU3MjU1Mzk@._V1_SX300.jpg"},{"Title":"REC","Year":"1999","imdbID":"tt0258069","Type":"movie","Poster":"N/A"},
    {"Title":"The Devils","Year":"1971","imdbID":"tt0066993","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNzA1NmM3NDktYzRkMi00NjZjLThiNjAtMWM2NjhiY2JlM2NmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Devils on the Doorstep","Year":"2000","imdbID":"tt0245929","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTMzMTUwNjQwNl5BMl5BanBnXkFtZTcwMjk2NTgyMQ@@._V1_SX300.jpg"},{"Title":"Tasmanian Devils","Year":"2013","imdbID":"tt2180543","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMzhhYzZkMDMtOWE3Yi00YzU4LWEzYTMtZmM5MWIwOTljZjZjXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg"},{"Title":"The Devils","Year":"2002","imdbID":"tt0291131","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTY1MzMxODgxMl5BMl5BanBnXkFtZTcwMTgxMTM1OQ@@._V1_SX300.jpg"},{"Title":"The Doctor and the Devils","Year":"1985","imdbID":"tt0089034","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjdkZGVlM2MtMmMxMi00YzBmLTlhMDUtOTAxOTJlNDNhYTJiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Night of the Devils","Year":"1972","imdbID":"tt0069017","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjc4NzNhNTItMGJmNS00ZDRiLWFkOTktNjRkODUzYWZkMzdiXkEyXkFqcGdeQXVyMjA0MzYwMDY@._V1_SX300.jpg"},{"Title":"She-Devils on Wheels","Year":"1968","imdbID":"tt0063595","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTBkMTBjNzEtOWYwZC00NzdmLThiOGYtMTA3ODRmZTI2ZjBjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},{"Title":"Blood Orgy of the She-Devils","Year":"1973","imdbID":"tt0068288","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTM2MDkyNjM5MF5BMl5BanBnXkFtZTcwMTg1MDUxMQ@@._V1_SX300.jpg"},{"Title":"Devils of Darkness","Year":"1965","imdbID":"tt0059100","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTYxMTAyMzI4Ml5BMl5BanBnXkFtZTcwNDQ1ODA1MQ@@._V1_SX300.jpg"},{"Title":"Sea Devils","Year":"1953","imdbID":"tt0046286","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1NjA1MjE1Ml5BMl5BanBnXkFtZTcwNDIxNjk5Mw@@._V1_SX300.jpg"},
]


arraySeries=[
    {"Title":"Game of Thrones","Year":"2011–","Rated":"TV-MA","Released":"17 Apr 2011","Runtime":"57 min","Genre":"Action, Adventure, Drama, Fantasy, Romance","Director":"N/A","Writer":"David Benioff, D.B. Weiss","Actors":"Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington","Plot":"Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.","Language":"English","Country":"USA, UK","Awards":"Won 1 Golden Globe. Another 273 wins & 454 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjE3NTQ1NDg1Ml5BMl5BanBnXkFtZTgwNzY2NDA0MjI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,403,052","imdbID":"tt0944947","Type":"series","totalSeasons":"8","Response":"True"},
    {"Title":"Friends","Year":"1994–2004","Rated":"TV-14","Released":"22 Sep 1994","Runtime":"22 min","Genre":"Comedy, Romance","Director":"N/A","Writer":"David Crane, Marta Kauffman","Actors":"Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc","Plot":"Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.","Language":"English, Dutch, Italian, French","Country":"USA","Awards":"Won 1 Golden Globe. Another 68 wins & 211 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"}],"Metascore":"N/A","imdbRating":"8.9","imdbVotes":"648,972","imdbID":"tt0108778","Type":"series","totalSeasons":"10","Response":"True"},
    {"Title":"The Big Bang Theory","Year":"2007–","Rated":"TV-14","Released":"01 May 2006","Runtime":"22 min","Genre":"Comedy, Romance","Director":"N/A","Writer":"Chuck Lorre, Bill Prady","Actors":"Kaley Cuoco, Johnny Galecki, Jim Parsons, Simon Helberg","Plot":"A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.","Language":"English, Hindi, Italian, Russian, Mandarin, Klingon","Country":"USA","Awards":"Won 1 Golden Globe. Another 66 wins & 222 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"}],"Metascore":"N/A","imdbRating":"8.2","imdbVotes":"631,440","imdbID":"tt0898266","Type":"series","totalSeasons":"12","Response":"True"},
    {"Title":"Sex and the City","Year":"2008","Rated":"R","Released":"30 May 2008","Runtime":"145 min","Genre":"Comedy, Drama, Romance","Director":"Michael Patrick King","Writer":"Michael Patrick King, Candace Bushnell (book), Darren Star (television series creator)","Actors":"Sarah Jessica Parker, Kim Cattrall, Kristin Davis, Cynthia Nixon","Plot":"A New York City writer on sex and love is finally getting married to her Mr. Big. But her three best girlfriends must console her after one of them inadvertently leads Mr. Big to jilt her.","Language":"English","Country":"USA","Awards":"2 wins & 12 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTYyMzYxMjM3OF5BMl5BanBnXkFtZTcwNjg2OTA3MQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.6/10"},{"Source":"Rotten Tomatoes","Value":"49%"},{"Source":"Metacritic","Value":"53/100"}],"Metascore":"53","imdbRating":"5.6","imdbVotes":"108,921","imdbID":"tt1000774","Type":"movie","DVD":"23 Sep 2008","BoxOffice":"$152,595,674","Production":"Warner Bros. Pictures","Website":"http://www.sexandthecitymovie.com/","Response":"True"},
    {"Title":"The Simpsons","Year":"1989–","Rated":"TV-PG","Released":"17 Dec 1989","Runtime":"22 min","Genre":"Animation, Comedy","Director":"N/A","Writer":"James L. Brooks, Matt Groening, Sam Simon","Actors":"Dan Castellaneta, Nancy Cartwright, Harry Shearer, Julie Kavner","Plot":"The satiric adventures of a working-class family in the misfit city of Springfield.","Language":"English, Spanish, Albanian, French, Japanese, German, Russian, Hindi, Swahili, Italian, Swedish, Turkish, Cantonese, Mandarin, Hebrew, Arabic, Klingon, Bengali, Czech","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 168 wins & 302 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYjFkMTlkYWUtZWFhNy00M2FmLThiOTYtYTRiYjVlZWYxNmJkXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.7/10"}],"Metascore":"N/A","imdbRating":"8.7","imdbVotes":"326,612","imdbID":"tt0096697","Type":"series","totalSeasons":"30","Response":"True"},
    {"Title":"Lost","Year":"2004–2010","Rated":"TV-14","Released":"22 Sep 2004","Runtime":"44 min","Genre":"Adventure, Drama, Fantasy, Mystery, Sci-Fi, Thriller","Director":"N/A","Writer":"J.J. Abrams, Jeffrey Lieber, Damon Lindelof","Actors":"Jorge Garcia, Josh Holloway, Yunjin Kim, Evangeline Lilly","Plot":"The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.","Language":"English, Portuguese, Spanish, Arabic, French, Korean, German, Latin, Russian, Japanese","Country":"USA","Awards":"Won 1 Golden Globe. Another 105 wins & 376 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzhlY2E5NDUtYjJjYy00ODg3LWFkZWQtYTVmMzU4ZWZmOWJkXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"80%"}],"Metascore":"N/A","imdbRating":"8.4","imdbVotes":"448,523","imdbID":"tt0411008","Type":"series","totalSeasons":"6","Response":"True"},
    {"Title":"Desperate Housewives","Year":"2004–2012","Rated":"TV-14","Released":"03 Oct 2004","Runtime":"45 min","Genre":"Comedy, Drama, Mystery, Romance","Director":"N/A","Writer":"Marc Cherry","Actors":"Teri Hatcher, Felicity Huffman, Marcia Cross, Eva Longoria","Plot":"Secrets and truths unfold through the lives of female friends in one suburban neighborhood, after the mysterious suicide of a neighbor.","Language":"English","Country":"USA","Awards":"Won 3 Golden Globes. Another 62 wins & 180 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYzI2MTFjZDktYTZhNS00YTU2LWI5ZTMtM2MzNDU1YjNhNTJlXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"}],"Metascore":"N/A","imdbRating":"7.5","imdbVotes":"105,356","imdbID":"tt0410975","Type":"series","totalSeasons":"8","Response":"True"},
    {"Title":"Breaking Bad","Year":"2008–2013","Rated":"TV-MA","Released":"20 Jan 2008","Runtime":"49 min","Genre":"Crime, Drama, Thriller","Director":"N/A","Writer":"Vince Gilligan","Actors":"Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris","Plot":"A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.","Language":"English, Spanish","Country":"USA","Awards":"Won 2 Golden Globes. Another 144 wins & 225 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.5/10"}],"Metascore":"N/A","imdbRating":"9.5","imdbVotes":"1,156,470","imdbID":"tt0903747","Type":"series","totalSeasons":"5","Response":"True"},
    {"Title":"Orange Is the New Black","Year":"2013–","Rated":"TV-MA","Released":"11 Jul 2013","Runtime":"59 min","Genre":"Comedy, Crime, Drama","Director":"N/A","Writer":"Jenji Kohan","Actors":"Taylor Schilling, Kate Mulgrew, Uzo Aduba, Danielle Brooks","Plot":"Convicted of a decade old crime of transporting drug money to an ex-girlfriend, normally law-abiding Piper Chapman is sentenced to a year and a half behind bars to face the reality of how life-changing prison can really be.","Language":"English","Country":"USA","Awards":"Nominated for 6 Golden Globes. Another 46 wins & 120 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA3MTE5ODM3M15BMl5BanBnXkFtZTgwNTIyMjQ5NTM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"}],"Metascore":"N/A","imdbRating":"8.1","imdbVotes":"249,149","imdbID":"tt2372162","Type":"series","totalSeasons":"7","Response":"True"},
    {"Title":"American Horror Story","Year":"2011–","Rated":"TV-MA","Released":"05 Oct 2011","Runtime":"60 min","Genre":"Drama, Horror, Thriller","Director":"N/A","Writer":"Brad Falchuk, Ryan Murphy","Actors":"Evan Peters, Sarah Paulson, Denis O'Hare, Kathy Bates","Plot":"An anthology series centering on different characters and locations, including a house with a murderous past, an insane asylum, a witch coven, a freak show, a hotel, a possessed farmhouse, a cult, and the apocalypse.","Language":"English","Country":"USA","Awards":"Won 2 Golden Globes. Another 111 wins & 317 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNTIzNDM1NjkwOV5BMl5BanBnXkFtZTgwNDU4ODgxNjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"}],"Metascore":"N/A","imdbRating":"8.1","imdbVotes":"245,418","imdbID":"tt1844624","Type":"series","totalSeasons":"9","Response":"True"},
    {"Title":"The Walking Dead","Year":"2010–","Rated":"TV-MA","Released":"31 Oct 2010","Runtime":"44 min","Genre":"Drama, Horror, Sci-Fi, Thriller","Director":"N/A","Writer":"Frank Darabont, Angela Kang","Actors":"Norman Reedus, Melissa McBride, Andrew Lincoln, Lauren Cohan","Plot":"Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins, and must lead a group of survivors to stay alive.","Language":"English","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 67 wins & 190 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDM2OTA1NzIzMV5BMl5BanBnXkFtZTgwOTkxMTk5NjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.3/10"}],"Metascore":"N/A","imdbRating":"8.3","imdbVotes":"771,193","imdbID":"tt1520211","Type":"series","totalSeasons":"9","Response":"True"},
    {"Title":"Stranger Things","Year":"2016–","Rated":"TV-14","Released":"15 Jul 2016","Runtime":"51 min","Genre":"Drama, Fantasy, Horror, Mystery, Sci-Fi, Thriller","Director":"N/A","Writer":"Matt Duffer, Ross Duffer","Actors":"Winona Ryder, David Harbour, Finn Wolfhard, Millie Bobby Brown","Plot":"When a young boy disappears, his mother, a police chief, and his friends must confront terrifying forces in order to get him back.","Language":"English","Country":"USA","Awards":"Nominated for 4 Golden Globes. Another 32 wins & 114 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTk3NTc2NTI0N15BMl5BanBnXkFtZTgwMDA4MjcwNzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"}],"Metascore":"N/A","imdbRating":"8.9","imdbVotes":"554,866","imdbID":"tt4574334","Type":"series","totalSeasons":"3","Response":"True"},
    {"Title":"Two and a Half Men","Year":"2003–2015","Rated":"TV-14","Released":"22 Sep 2003","Runtime":"22 min","Genre":"Comedy, Romance","Director":"N/A","Writer":"Lee Aronsohn, Chuck Lorre","Actors":"Jon Cryer, Angus T. Jones, Conchata Ferrell, Charlie Sheen","Plot":"A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.","Language":"English","Country":"USA","Awards":"Nominated for 2 Golden Globes. Another 29 wins & 70 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTI2MjIzN2ItZDg0OS00MTlhLWIzMTMtYWI4ZTA0NGE4NDJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"}],"Metascore":"N/A","imdbRating":"7.1","imdbVotes":"224,150","imdbID":"tt0369179","Type":"series","totalSeasons":"12","Response":"True"},
    {"Title":"The Middle","Year":"2009–2018","Rated":"TV-PG","Released":"30 Sep 2009","Runtime":"22 min","Genre":"Comedy","Director":"N/A","Writer":"Eileen Heisler, DeAnn Heline","Actors":"Patricia Heaton, Neil Flynn, Charlie McDermott, Eden Sher","Plot":"The daily mishaps of a married woman and her semi-dysfunctional family and their attempts to survive life in general in the town of Orson, Indiana.","Language":"English","Country":"USA","Awards":"Nominated for 1 Primetime Emmy. Another 11 wins & 34 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMGQ3ZDAxMzQtZDlkNS00OTJjLTk3ZDEtZjc4NDVkZjM1NTk5XkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"}],"Metascore":"N/A","imdbRating":"7.5","imdbVotes":"40,151","imdbID":"tt1442464","Type":"series","totalSeasons":"9","Response":"True"},
    {"Title":"House of Cards","Year":"2013–2018","Rated":"TV-MA","Released":"01 Feb 2013","Runtime":"51 min","Genre":"Drama","Director":"N/A","Writer":"Beau Willimon","Actors":"Robin Wright, Michael Kelly, Kevin Spacey, Justin Doescher","Plot":"A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.","Language":"English","Country":"USA","Awards":"Won 2 Golden Globes. Another 27 wins & 198 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BODM1MDU2NjY5NF5BMl5BanBnXkFtZTgwMDkxNTcwNjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"}],"Metascore":"N/A","imdbRating":"8.8","imdbVotes":"423,103","imdbID":"tt1856010","Type":"series","totalSeasons":"6","Response":"True"},
    {"Title":"Dexter","Year":"2006–2013","Rated":"TV-MA","Released":"01 Oct 2006","Runtime":"53 min","Genre":"Crime, Drama, Mystery, Thriller","Director":"N/A","Writer":"James Manos Jr.","Actors":"Michael C. Hall, Jennifer Carpenter, David Zayas, James Remar","Plot":"By day, mild-mannered Dexter is a blood-spatter analyst for the Miami police. But at night, he is a serial killer who only targets other murderers.","Language":"English, Spanish","Country":"USA","Awards":"Won 2 Golden Globes. Another 49 wins & 191 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTM5MjkwMTI0MV5BMl5BanBnXkFtZTcwODQwMTc0OQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.7/10"}],"Metascore":"N/A","imdbRating":"8.7","imdbVotes":"588,376","imdbID":"tt0773262","Type":"series","totalSeasons":"8","Response":"True"},
    {"Title":"Chicago Fire","Year":"2012–","Rated":"TV-14","Released":"N/A","Runtime":"43 min","Genre":"Action, Drama","Director":"N/A","Writer":"Michael Brandt, Derek Haas","Actors":"Jesse Spencer, Taylor Kinney, Eamonn Walker, Yuri Sardarov","Plot":"The story of firefighters in Chicago, both on a personal and professional level.","Language":"English","Country":"USA","Awards":"4 wins & 19 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYmU2MTUyM2QtYmI2YS00OTY3LTk0YmQtMTk4ZGE1NGE1ZTNkXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"}],"Metascore":"N/A","imdbRating":"7.9","imdbVotes":"29,773","imdbID":"tt2261391","Type":"series","totalSeasons":"7","Response":"True"},
    {"Title":"Narcos","Year":"2015–2017","Rated":"TV-MA","Released":"28 Aug 2015","Runtime":"49 min","Genre":"Biography, Crime, Drama, Thriller","Director":"N/A","Writer":"Carlo Bernard, Chris Brancato, Doug Miro, Paul Eckstein","Actors":"Pedro Pascal, Wagner Moura, Boyd Holbrook, Alberto Ammann","Plot":"A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.","Language":"English, Spanish","Country":"Colombia, USA","Awards":"Nominated for 2 Golden Globes. Another 6 wins & 15 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNmU5ZGQyZDUtMmU3OC00ZTZkLTk4YzItYzg5NDNkMmJlZjMwXkEyXkFqcGdeQXVyNjU2ODM5MjU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"}],"Metascore":"N/A","imdbRating":"8.8","imdbVotes":"280,799","imdbID":"tt2707408","Type":"series","totalSeasons":"4","Response":"True"},
    {"Title":"Pablo Escobar","Year":"2015","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"Drama, Thriller","Director":"Ranjeet S. Marwa","Writer":"Ranjeet S. Marwa","Actors":"James Bryhan, Chandni Supawala","Plot":"There can only be one Don, Pablo Escobar.","Language":"English","Country":"N/A","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BYWM5ZjljNDQtMzIwNS00ZmZiLWE1MWUtNjAxYmIyNDUyMGRlXkEyXkFqcGdeQXVyNjUxOTkzOTk@._V1_.jpg","Ratings":[],"Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt4505682","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"},
    {"Title":"Sherlock","Year":"2010–","Rated":"TV-14","Released":"24 Oct 2010","Runtime":"88 min","Genre":"Crime, Drama, Mystery, Thriller","Director":"N/A","Writer":"Mark Gatiss, Steven Moffat","Actors":"Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves","Plot":"A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.","Language":"English","Country":"UK, USA","Awards":"Nominated for 1 Golden Globe. Another 86 wins & 159 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTQ4NTc5OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.2/10"}],"Metascore":"N/A","imdbRating":"9.2","imdbVotes":"684,671","imdbID":"tt1475582","Type":"series","totalSeasons":"4","Response":"True"},
    {"Title":"La casa de papel","Year":"2017–","Rated":"TV-MA","Released":"02 May 2017","Runtime":"70 min","Genre":"Action, Crime, Mystery, Thriller","Director":"N/A","Writer":"Álex Pina","Actors":"Úrsula Corberó, Itziar Ituño, Álvaro Morte, Alba Flores","Plot":"A group of very peculiar robbers assault the Factory of Moneda and Timbre to carry out the most perfect robbery in the history of Spain and take home 2.4 billion euros.","Language":"Spanish, Russian, Serbian, English","Country":"Spain","Awards":"3 wins & 12 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzBlY2QzNzYtMWU1NS00NjFkLWJiMzItYmM3YTc4MDFjNDQwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"}],"Metascore":"N/A","imdbRating":"8.6","imdbVotes":"112,294","imdbID":"tt6468322","Type":"series","totalSeasons":"3","Response":"True"},
    {"Title":"Doctor Who","Year":"2005–","Rated":"TV-PG","Released":"17 Mar 2006","Runtime":"45 min","Genre":"Adventure, Drama, Family, Mystery, Sci-Fi","Director":"N/A","Writer":"Sydney Newman","Actors":"Matt Smith, David Tennant, Peter Capaldi, Jenna Coleman","Plot":"The further adventures in time and space of the alien adventurer known as the Doctor, a Time Lord/Lady who can change appearance and gender by regenerating when near death, and his/her human companions.","Language":"English","Country":"UK, Canada","Awards":"110 wins & 174 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDY1YmZhZjEtY2E3NC00M2VkLThlZmUtODczMmNiZjMxMWRhXkEyXkFqcGdeQXVyNzA5NTYxMDg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.7/10"}],"Metascore":"N/A","imdbRating":"8.7","imdbVotes":"181,216","imdbID":"tt0436992","Type":"series","totalSeasons":"12","Response":"True"},
    {"Title":"Elite","Year":"2018–","Rated":"TV-MA","Released":"05 Oct 2018","Runtime":"60 min","Genre":"Crime, Drama, Thriller","Director":"N/A","Writer":"Darío Madrona, Carlos Montero","Actors":"María Pedraza, Itzan Escamilla, Miguel Bernardeau, Miguel Herrán","Plot":"When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.","Language":"Spanish","Country":"Spain","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BOTgyOTIwODk3MV5BMl5BanBnXkFtZTgwNTE2MzEzNjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"}],"Metascore":"N/A","imdbRating":"7.6","imdbVotes":"14,413","imdbID":"tt7134908","Type":"series","totalSeasons":"3","Response":"True"},
    {"Title":"True Blood","Year":"2008–2014","Rated":"TV-MA","Released":"07 Sep 2008","Runtime":"55 min","Genre":"Drama, Fantasy, Mystery, Romance, Thriller","Director":"N/A","Writer":"Alan Ball","Actors":"Anna Paquin, Stephen Moyer, Sam Trammell, Ryan Kwanten","Plot":"Telepathic waitress Sookie Stackhouse encounters a strange new supernatural world when she meets the mysterious Bill, a southern Louisiana gentleman and vampire.","Language":"English, German, Swedish, Russian","Country":"USA","Awards":"Won 1 Golden Globe. Another 36 wins & 155 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMDVjZDQ2N2MtMzMxYy00ZjliLTg5YjAtNjk1OTUwYjVjNWQ0XkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.9/10"}],"Metascore":"N/A","imdbRating":"7.9","imdbVotes":"217,292","imdbID":"tt0844441","Type":"series","totalSeasons":"7","Response":"True"},


]


const Action = document.getElementById("Action");
Action.addEventListener("click", () => {
   forMovieGenre(arrayAction);
   
});


const forMovieGenre = (dataMovie) =>{
    //dataMovie= JSON.parse(localStorage.getItem("data"));
    printMovie.innerHTML="";
    showGenre.innerHTML="";
    dataMovie.forEach(element => {
 let showMovie =
`<div class = "cardMovie">
<figure class ="imgMovie"><img class = "imagen"src = "${element.Poster}"></figure>
<div class ="infoMovie">
<h2>Title:${element.Title}</h2>
<p>Year: ${element.Year}</p>
<p>Type: ${element.Type}</p></div>
</div>`

showGenre.insertAdjacentHTML("beforeend",showMovie)
    })
   }

const Fiction = document.getElementById("Fiction");

Fiction.addEventListener("click", () =>{
    forMovieGenre(arrayFiction);
})

const Horror = document.getElementById("Horror");

Horror.addEventListener("click", () => {
    forMovieGenre(arrayHorror);
})

const series = document.getElementById("Series");

series.addEventListener("click", () => {
    forMovieGenre(arraySeries);
})

//funcionamiento de imagenes de sugerencia
$(".img").mousemove(function(event){
    var mouse = event.pageX - $(this).offset().left;
    var mousea = event.pageY - $(this).offset().top;
   
    var imgx = (mouse - 300) / 40;
    var imgy = (mousea - 200) / 40;
   
    $(this).css("transform", "translate(" + imgx + "px," + imgy + "px)");
  });

  $(".img").mouseout(function(){
    $(this).css("transform", "translate(0px,0px)");
  });
